version: '3.3'
services:
  db:
    image: mysql
    container_name: database
    volumes:
    - dbdata:/var/lib/mysql
    restart: always
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: psa
      MYSQL_DATABASE: psa
      MYSQL_USER: psa
      MYSQL_PASSWORD: psa
volumes:
  dbdata: